### ISSUE TITLE
requesting small edits

### ISSUE THREAD

**Issue by JackDougherty** [metrohistory/toronto-cma-income-areas#3]
@ilyankou please make a few more small edits
- [ ] add a small Leaflet north arrow to bottom-left corner, above scale
- [ ] move the toggle layer legend to the bottom-right corner (aka Lake Ontario - lots of space)
- [ ] in the upper-right choropleth scale, flip the text and numbers: if you place text on the top, in bold and larger font size, it doubles as a title. Move numbers below color line

Thanks!

**Comment by ilyankou** [comment]
All 3 implemented in #4

**Comment by ilyankou** [comment]
Ready to be closed?

**Comment by JackDougherty** [comment]
Jason and I love your map. Would you please make a few more edits? 

Our goal is to show how City of Toronto boundaries grew from 1966 to present, and also to use "dashed lines" to illustrate boundary lines that have been dissolved.

I have uploaded more boundary files to `geodata` folder, specifically this one:
toronto-city-pre1966-osm-edit.geojson

Please update the boundary legend (with these colors/styles) to display this way:

City of Toronto pre-1966 (black, dashed line, thick)
Toronto 1998-present (black, solid line, thick) [see toronto-boundary-2016-osm, or ...detailed-2012]
Etobicoke pre-1966 (orange, dashed line, thick)
York pre-1966 (magenta, dashed line, thick)
Forest Hill pre-1966 (purple [maybe #6600cc, to distinguish it from blue], dashed line, thick)
Scarborough pre-1966 (green, dashed line, thick)
Income 2015 for Toronto CMA (black, solid line, thin [which is what appears now]) 

thank you!

**Comment by ilyankou** [comment]
@JackDougherty 

Regarding the last item of the new legend (Income 2015 for Toronto CMA). Previously, **Income 2015** layer was choropleth, not the CMA boundary. Previously there was no way to disable the CMA boundary (it was not in the legend – these were your instructions).

I joined the thin black boundary of Toronto CMA and the choropleth into a FeatureGroup and added them as one item to the legend (last item – like you have in the list above), so now it disables both choropleth and the black boundary. Let me know if that makes sense, and if that's what you had in mind.

**Comment by JackDougherty** [comment]
looks great! thanks @ilyankou
